### ISSUE TITLE
Deep nesting example

### ISSUE THREAD

**Issue by crazy4groovy** [jviotti/queryl#10]
It would be great to see a deeply nested object example, to show off some more power.

Eg. 
```
{
  foo: {
    bar: [1, 2, {baz: 6}]
  }
}
```
Assert that:
- `foo.bar` contains 2?
- `foo.bar.baz` === 6?

**Comment by jviotti** [comment]
Hi @crazy4groovy ,

Thanks a lot for the suggestion. Nested objects is something Queryl currently doesn't support. Luckily, I have a patch that would allow such assertions.

I'll create a pull request in a second, and you'll be able to see some examples for it on the test suite.

**Comment by jviotti** [comment]
The following assertions should to the job once the patch I've just sent lands in the next Queryl version:

```js
queryl.match({
  $contain: {
    'foo.bar': 2
  }
}, {
  foo: {
    bar: [ 1, 2, 3 ]
  }
});
```
***
```js
queryl.match({
  $contain: {
    'foo.bar': {
      baz: 6
    }
  }
}, {
  foo: {
    bar: [ 1, 2, { baz: 6 } ]
  }
});
```

**Comment by jviotti** [comment]
@crazy4groovy I've released the above feature in v1.1.0 to NPM.

**Comment by crazy4groovy** [comment]
Update the readme? It's really useful stuff :)

**Comment by crazy4groovy** [comment]
Also I see you're using `_.get`; you could check out my `_.getPath` plugin for nested arrays, if you're interested ;)
https://github.com/crazy4groovy/lodash.getPath

**Comment by jviotti** [comment]
@crazy4groovy I'll definitely look into it! I've updated the README in the mid-time!
